### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Briefly tested and reviewed.

Couple of tracebacks appeared;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Speak.activity/brain.py", line 118, in load_brain
    kernel = Kernel()
  File "/usr/share/sugar/activities/Speak.activity/aiml/Kernel.py", line 36, in __init__
    self._brain = PatternMgr()
  File "/usr/share/sugar/activities/Speak.activity/aiml/PatternMgr.py", line 27, in __init__
    self._whitespaceRE = re.compile("\s", re.LOCALE)
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 940, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/lib/python3.7/sre_parse.py", line 907, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

and

```log
1572400794.801357 ERROR root: Error saving activity object to datastore
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 1274, in _prepare_close
    self.save()
  File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 947, in save
    buddies_dict = self._get_buddies()
  File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 920, in _get_buddies
    buddy_id = sha1(buddy.props.key).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

`io.open` is an alias for the builtin `open`.  Please don't use `io.open` instead of `open`, as none of the other ports have done that, and we save an import.

I made a temporary local branch containing the `2to3` changes only, so I could compare against your branch.  You could have saved me that step by making the `2to3` changes in a separate commit, as in https://github.com/sugarlabs/fractionbounce/commits/master.

In comparing the changes, I see you also changed use of Telepathy, but that wasn't in the commit message.  Reverting 30351171294c43f6288215086d03d4f57cf44d2e first could make the port commits simpler.

Also saw that TextChannelWrapper looks very much like what we have in CollabWrapper, with some changes.

Worried that you may have been overenthusiastic with the integer division; the one that divides by the result from `math.hypot` seems wrong, as does one that divides by the floating point constant `10.0`, and `_scale`.  Please check that each of the integer divisions you made didn't affect what were originally floating point values.

**Comment by chimosky** [comment]
> Thanks. Briefly tested and reviewed.
> 
> Couple of tracebacks appeared;
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/sugar/activities/Speak.activity/brain.py", line 118, in load_brain
>     kernel = Kernel()
>   File "/usr/share/sugar/activities/Speak.activity/aiml/Kernel.py", line 36, in __init__
>     self._brain = PatternMgr()
>   File "/usr/share/sugar/activities/Speak.activity/aiml/PatternMgr.py", line 27, in __init__
>     self._whitespaceRE = re.compile("\s", re.LOCALE)
>   File "/usr/lib/python3.7/re.py", line 234, in compile
>     return _compile(pattern, flags)
>   File "/usr/lib/python3.7/re.py", line 286, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib/python3.7/sre_parse.py", line 940, in parse
>     p.pattern.flags = fix_flags(str, p.pattern.flags)
>   File "/usr/lib/python3.7/sre_parse.py", line 907, in fix_flags
>     raise ValueError("cannot use LOCALE flag with a str pattern")
> ValueError: cannot use LOCALE flag with a str pattern
> ```

Got this error once but didn't get it again and it's no surprise that it's come up, I'll fix that.
> 
> and
> 
> ```
> 1572400794.801357 ERROR root: Error saving activity object to datastore
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 1274, in _prepare_close
>     self.save()
>   File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 947, in save
>     buddies_dict = self._get_buddies()
>   File "/usr/local/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 920, in _get_buddies
>     buddy_id = sha1(buddy.props.key).hexdigest()
> TypeError: Unicode-objects must be encoded before hashing
> ```

I don't get this error, and the logs seem to be pointing to the toolkit.

> 
> `io.open` is an alias for the builtin `open`. Please don't use `io.open` instead of `open`, as none of the other ports have done that, and we save an import.
> 

I used it cos it was stated in the python docs, I'll change it.
> I made a temporary local branch containing the `2to3` changes only, so I could compare against your branch. You could have saved me that step by making the `2to3` changes in a separate commit, as in https://github.com/sugarlabs/fractionbounce/commits/master.
> 

Will do. Thanks.

> In comparing the changes, I see you also changed use of Telepathy, but that wasn't in the commit message. Reverting [3035117](https://github.com/sugarlabs/speak/commit/30351171294c43f6288215086d03d4f57cf44d2e) first could make the port commits simpler.
> 

I'll do that.
> Also saw that TextChannelWrapper looks very much like what we have in CollabWrapper, with some changes.
> 

Yes they're both the same, this was an update of `TexhChannelWrapper`. I'll put it in a different commit.

> Worried that you may have been overenthusiastic with the integer division; the one that divides by the result from `math.hypot` seems wrong, as does one that divides by the floating point constant `10.0`, and `_scale`. Please check that each of the integer divisions you made didn't affect what were originally floating point values.

You're right the division of the result from `math.hypot` is a float. In `_scale`, all divisions were later converted to ints.

**Comment by quozl** [comment]
> Seems your toolkit isn't updated as [L923](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/activity/activity.py#L923) of the toolkit encodes the object before hashing.

Agreed.  Fixed.
 
> You're right the division of the result from `math.hypot` is a float. In `_scale`, all divisions were later converted to ints.

Thanks.

Tested again, nothing specific to the port seen.  Reproduced https://github.com/sugarlabs/speak/issues/21.

However, on looking through the flake8 changes, my test coverage is poor;

```log
voice.py:105:16: F821 undefined name 'cmp'
activity.py:1144:22: F821 undefined name 'PROPERTIES_IFACE'
activity.py:1145:25: F821 undefined name 'PROPERTIES_IFACE'
activity.py:1303:21: F821 undefined name 'CONNECTION_INTERFACE_ALIASING'
```

You'll need to fix the undefined names.

**Comment by chimosky** [comment]
> Tested again, nothing specific to the port seen. Reproduced #21.

Mouth movements happen but they aren't visible - clicking on any toolbar button shows you the mouth movement -, same thing happens when activity is resumed. I'll see what I find.

> 
> However, on looking through the flake8 changes, my test coverage is poor;
> 
> ```
> voice.py:105:16: F821 undefined name 'cmp'
> activity.py:1144:22: F821 undefined name 'PROPERTIES_IFACE'
> activity.py:1145:25: F821 undefined name 'PROPERTIES_IFACE'
> activity.py:1303:21: F821 undefined name 'CONNECTION_INTERFACE_ALIASING'
> ```
> 
> You'll need to fix the undefined names.

Fixed in 02f32ed.

**Comment by quozl** [comment]
Thanks.  Added a couple of review commits.  There's still an _undefined name 'cmp'_ though.  New issue https://github.com/sugarlabs/speak/issues/26 unrelated to port.

**Comment by chimosky** [comment]
Thanks, noticed #26 happens for all eyes.

**Comment by quozl** [comment]
Thanks.  I've re-organised the patches in preparation for merging, and made one more test, but hit a problem with the AI.

```
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Speak.activity/brain.py", line 117, in load_brain
    kernel = Kernel()
  File "/usr/share/sugar/activities/Speak.activity/aiml/Kernel.py", line 45, in __init__
    self.setBotPredicate("name", "Nameless")
  File "/usr/share/sugar/activities/Speak.activity/aiml/Kernel.py", line 212, in setBotPredicate
    self._brain.setBotName(self.getBotPredicate("name"))
  File "/usr/share/sugar/activities/Speak.activity/aiml/PatternMgr.py", line 38, in setBotName
    self._botName = str(string.join(name.split()))
AttributeError: module 'string' has no attribute 'join'
```

Can you confirm you tested the AI?  The lightbulb "Ask robot any question" button.  It works with _master_ branch.

**Comment by chimosky** [comment]
> Can you confirm you tested the AI? The lightbulb "Ask robot any question" button. It works with master branch.

Faced some issues with the AI earlier but I didn't take note of the log lines for it, skipped because I was looking for something else in the logs. 
Changes made, kindly test and review. Thanks.

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Changes made are huge, and it will take a long time to do a code review.  After a quick look, you seem to have restored the content removed in b5a3bf9a185374252912103f49c4e65c77e33dbe by duplicating content between `bot/` and `aiml/botdata`?  Are all the new files required?

**Comment by chimosky** [comment]
@quozl kindly review.

> Thanks. Changes made are huge, and it will take a long time to do a code review. 

411a63c is an update of the upstream, you can take a look at the [upstream](https://github.com/paulovn/python-aiml/tree/master/aiml) to verify.

> After a quick look, you seem to have restored the content removed in [b5a3bf9](https://github.com/sugarlabs/speak/commit/b5a3bf9a185374252912103f49c4e65c77e33dbe) by duplicating content between `bot/` and `aiml/botdata`? Are all the new files required?

All the new files aren't required but `aiml/botdata` is more comprehensive than `bot/`, I can revert the commit also leaving the change in b5a3bf9 - it could also be in another commit -.
What do you suggest?

**Comment by quozl** [comment]
Only files that are required should be present.  Files that are not used are a distraction for maintainers.

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed 4c9f095.

I'm concerned the python-aiml repository contains changes to the aiml files for compatibility with changes made to the python files, yet you're combining the new python files with the old aiml files.  I think you should merge our changes to the aiml files with the changes made in python-aiml, so that we get;

* compatible aiml and python,
* changes we made such as https://github.com/sugarlabs/speak/commit/b5a3bf9a185374252912103f49c4e65c77e33dbe,
* changes made by others in python-aiml repository.

Otherwise there's a risk that the AI won't respond correctly.  We don't have enough testers to test it as much as we did back when https://github.com/sugarlabs/speak/commit/b5a3bf9a185374252912103f49c4e65c77e33dbe was done, so we have to be more careful.

**Comment by chimosky** [comment]
> Thanks. Reviewed [4c9f095](https://github.com/sugarlabs/speak/commit/4c9f09551a6c6a77cafbfb8efa65e9181979c58b).
> 
> I'm concerned the python-aiml repository contains changes to the aiml files for compatibility with changes made to the python files, yet you're combining the new python files with the old aiml files. I think you should merge our changes to the aiml files with the changes made in python-aiml, so that we get;

It's a possibility, `aim/botdata/alice/*.aiml` is more comprehensive than what we have at `bot/alice/*.aiml`. I'll look at moving the files from `botdata/` to `bot` as we use that to compile the brain.

**Comment by chimosky** [comment]
b5a3bf9 doesn't seem to handle all cases of such changes, I'll remove everything related to religion.

**Comment by quozl** [comment]
Thanks.  I'm not surprised.  It was a response to complaints, and some
keywords may have been missed.

Please commit your additional religion removal changes in a separate
patch, so that anyone who wants them back for a local deployment can
revert the patch.

**Comment by chimosky** [comment]
> Thanks. I'm not surprised. It was a response to complaints, and some keywords may have been missed. Please commit your additional religion removal changes in a separate patch, so that anyone who wants them back for a local deployment can revert the patch.

Will do.

While deleting objectionable content, they're certain things I'd like your opinion and others opinions on. @aperezbios @pikurasa
* The rape content contained in the files, which is appropriate for the activity.
* The content referring to GOD(s), is Greek mythology allowed. 
* The content regards sex and Male and female genitals.

I could have given some instances of such but I'm not done with the removal of content, kindly search 4c9f095 for instances.

**Comment by chimosky** [comment]
@quozl will this be merged now or is there something else you'd like me to do.
I'll be restoring 4c9f095 in the new patch I'll send.

**Comment by quozl** [comment]
I'll review again.  All this time we've relied on plausible deniability.  I may have to reconsider inclusion in OLPC OS of the AI feature.

**Comment by rabbitholecomputing** [comment]
As of now, I'm of the opinion that this content is not a problem, really, only a hypothetical one, and if it were going to have been one, it probably would have come up at some point over the last decade.

**Comment by aperezbios** [comment]
As of now, I'm of the opinion that this content is not a problem, really, only a hypothetical one, and if it were going to have been one, it probably would have come up at some point over the last decade.

**Comment by chimosky** [comment]
> As of now, I'm of the opinion that this content is not a problem, really, only a hypothetical one, and if it were going to have been one, it probably would have come up at some point over the last decade.

I agree with Alex and if anyone wants to make the change for a local deployment they can do that.
I also think we should replace `bot/alice/` and `bot/alischoka/` with `botdata/alice/` and `botdata/standard` as they're both updated and more comprehensive.

**Pull request merged**
