### PR TITLE
Port to GTK 3 and GStreamer 1.0, v53

### PR DESCRIPTION
**Pull request by quozl**
* Port from GTK 2 to GTK3.
* Port from GStreamer 0.1 to GStreamer 1.0,
* Several bugs fixed.

Based on earlier work by @cristian99garcia.

### CODE REVIEW

**Comment by walterbender** [comment]
At some point, it would good to have someone move from boxes to grid. Perhaps a GCI task next year?

**Comment by quozl** [comment]
Thanks for merging.

Not sure what would be the benefit.  I'm familiar with `Gtk.Grid` and could have used it, but `Gtk.Box` is conceptually easier and is already in use.  There did seem to be an excessive use, where widgets were boxed unnecessarily, and I removed many of those in this patch.

(Funny how things come around; once upon a time I coded with Motif, and the [`Form` widget](http://www.ist.co.uk/motif/books/vol6A/ch-8.fm.html#543567) class looks just like the `Gtk.Grid`'s `attach` method.)

**Comment by walterbender** [comment]
Personally, I find grid to be much easier to use, Regardless, I thought box was deprecated.  But if not, then we should leave it as is.

**Comment by quozl** [comment]
Yes, gtk.Box was deprecated in GTK 2 in favour of gtk.VBox and gtk.HBox.  Recently in GTK 3 the reverse was done.  There's still some Gtk.VBox and Gtk.HBox to be removed.

**Pull request merged**
